### ISSUE TITLE
'onclick' type of 'this' is wrong

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-DOM-lib-generator#564]
```ts
document.body.onclick = function() {
    console.log(this.innerHTML.length);
}
```

The code works in a browser and worked in `typescript@3.0`. But in `typescript@3.1.0-dev.20180804` it is a compile error: 

```
src/a.ts:3:22 - error TS2339: Property 'innerHTML' does not exist on type 'GlobalEventHandlers'.

3     console.log(this.innerHTML.length);
```

The value of `this` should be `HTMLElement` like it was before, not `GlobalEventHandlers`.
Detected in `fabric` and `tingle.js` on DefinitelyTyped.

**Comment by latot** [comment]
Hi, this still is present in v3.9.5, I found it with ```onchange```....

**Comment by Bashamega** [comment]
This error is still present in version 5.8
[Playground](https://www.typescriptlang.org/play/?#code/CYewxgrgtgpgdgFwHQCMTAJ5JHMAbASzAGsACAXlIDMJcECcAKASlIG8AoU70sHAZxB4YSPCADmjBAAsC-JAThwYAJwASAFQCyAGVHxxM5gG4OAXyA)
